# Generated by Django 4.2 on 2025-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_field', models.DateField()),
            ],
        ),
    ]
